### ISSUE TITLE
Make foes that are killed display a different animation

### ISSUE THREAD

**Issue by theTrueMikeBrown** [PretentiousGames/towerDefense#10]

**Comment by tehscott** [comment]
Made foes explode in a shower of blood. Video here: https://www.dropbox.com/s/k4vgj5nuwzyjwkx/blood_splatter.webm?dl=0

**Comment by tehscott** [comment]
See a video here: https://www.dropbox.com/s/k4vgj5nuwzyjwkx/blood_splatter.webm?dl=0

**Comment by theTrueMikeBrown** [comment]
Excellent!
